# Generated by Django 5.2 on 2025-05-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users_data_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_data',
            name='userid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
