# Generated by Django 5.2 on 2025-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('email', models.TextField(max_length=500)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
