# Generated by Django 5.2 on 2025-04-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_alter_products_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.PositiveIntegerField(),
        ),
    ]
