# Generated by Django 5.2 on 2025-05-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_products_buyer_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('image', models.ImageField(default='default.jpg', upload_to='imgs/')),
                ('user_id', models.TextField(max_length=100)),
            ],
        ),
    ]
