# Generated by Django 5.2 on 2025-05-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_users_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_product',
            old_name='prod_name',
            new_name='title',
        ),
    ]
